---
- import_playbook: ./vbox_load_vars.yml
- import_playbook: ./sudo.yml
- hosts: all
  pre_tasks:
  - shell: docker ps
    failed_when: false
    changed_when: false
    register: cops_docker_test1
    no_log: true
  - shell: grep -q mtu /etc/default/docker
    register: cops_docker_test2
    changed_when: false
    failed_when: false
    no_log: true
  roles:
  - role: corpusops.roles/services_virt_docker
    when: >-
      ((not vbox_cops.get('SKIP_INSTALL_DOCKER', False)) and
       ((cops_docker_test2.rc !=0) or
       (cops_docker_test1.rc !=0)))
